import React, { useEffect, useState } from "react";
import { MoviesList } from "../components/MoviesCollection/MoviesList";
import * as movieApi from "../helpers/moviesApi";

const tempData = [
  {
    adult: false,
    backdrop_path: "/qHdPNd1cUaSNYLLNgt1Pv3LVd0T.jpg",
    id: 843794,
    title: "JUNG_E",
    original_language: "ko",
    original_title: "정이",
    overview:
      "On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.",
    poster_path: "/2LAtcGxhgfPmaKL7dItQ1n9TepH.jpg",
    media_type: "movie",
    genre_ids: [878, 28, 12],
    popularity: 100.932,
    release_date: "2023-01-20",
    video: false,
    vote_average: 5.7,
    vote_count: 29,
  },
  {
    adult: false,
    backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    id: 76600,
    title: "Avatar: The Way of Water",
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    media_type: "movie",
    genre_ids: [878, 12, 28],
    popularity: 2552.263,
    release_date: "2022-12-14",
    video: false,
    vote_average: 7.715,
    vote_count: 4427,
  },
  {
    adult: false,
    backdrop_path: "/r9PkFnRUIthgBp2JZZzD380MWZy.jpg",
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    original_language: "en",
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    media_type: "movie",
    genre_ids: [16, 28, 12, 35, 10751, 14],
    popularity: 8303.733,
    release_date: "2022-12-07",
    video: false,
    vote_average: 8.623,
    vote_count: 2211,
  },
  {
    adult: false,
    backdrop_path: "/jJbEKl69hgNdQ9vQISqQGEDx4Lh.jpg",
    id: 632065,
    title: "House Party",
    original_language: "en",
    original_title: "House Party",
    overview:
      "Aspiring club promoters and best buds Damon and Kevin are barely keeping things together. Out of money, down on their luck and about to lose the roofs over their heads—and freshly fired from their low-lift jobs as house cleaners—the pair needs a huge windfall to make their problems go away. In a ‘what the hell?’ move, they decide to host the party of the year at an exclusive mansion, the site of their last cleaning job, which just happens to belong to none other than LeBron James. No permission? No problem. What could go wrong?",
    poster_path: "/KiyKR9m6h01eIvGObGmpt16U3F.jpg",
    media_type: "movie",
    genre_ids: [35],
    popularity: 171.608,
    release_date: "2023-01-12",
    video: false,
    vote_average: 7.1,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/5pMy5LF2JAleBNBtuzizfCMWM7k.jpg",
    id: 653851,
    title: "Devotion",
    original_language: "en",
    original_title: "Devotion",
    overview:
      "The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy's most celebrated wingmen.",
    poster_path: "/26yQPXymbWeCLKwcmyL8dRjAzth.jpg",
    media_type: "movie",
    genre_ids: [10752, 36, 18],
    popularity: 2190.076,
    release_date: "2022-11-23",
    video: false,
    vote_average: 6.9,
    vote_count: 69,
  },
  {
    adult: false,
    backdrop_path: "/mSyQoValhBsJdq3JNGXJww2Q5yL.jpg",
    id: 593643,
    title: "The Menu",
    original_language: "en",
    original_title: "The Menu",
    overview:
      "A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.",
    poster_path: "/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg",
    media_type: "movie",
    genre_ids: [35, 27, 53],
    popularity: 411.64,
    release_date: "2022-11-18",
    video: false,
    vote_average: 7.31,
    vote_count: 1686,
  },
  {
    adult: false,
    backdrop_path: "/m7YAaJllW6XmUjfiT9ZolNOr6HO.jpg",
    id: 996727,
    title: "The Price We Pay",
    original_language: "en",
    original_title: "The Price We Pay",
    overview:
      "After a pawn shop robbery goes askew, two criminals take refuge at a remote farmhouse to try to let the heat die down, but find something much more menacing.",
    poster_path: "/8fwJt0qZieQ7dKaiiqehObWpXYT.jpg",
    media_type: "movie",
    genre_ids: [28, 53, 9648, 80, 27],
    popularity: 37.701,
    release_date: "2023-01-13",
    video: false,
    vote_average: 5.143,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/a4I481szRmycyreQTLrRe4f4YJe.jpg",
    id: 842544,
    title: "Transfusion",
    original_language: "en",
    original_title: "Transfusion",
    overview:
      "Ryan Logan, a former Special Forces operative, is battling to cope with life after the loss of his wife.  He is thrusted into the criminal underworld to keep his only son from being taken from him.",
    poster_path: "/jOqHkfg4F53aR77PcuAqflKkvGE.jpg",
    media_type: "movie",
    genre_ids: [18, 53],
    popularity: 13.418,
    release_date: "2023-01-05",
    video: false,
    vote_average: 5.6,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/5kAGbi9MFAobQTVfK4kWPnIfnP0.jpg",
    id: 536554,
    title: "M3GAN",
    original_language: "en",
    original_title: "M3GAN",
    overview:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    poster_path: "/7CNCv9uhqdwK7Fv4bR4nmDysnd9.jpg",
    media_type: "movie",
    genre_ids: [878, 27, 35],
    popularity: 3751.058,
    release_date: "2022-12-28",
    video: false,
    vote_average: 7.1,
    vote_count: 354,
  },
  {
    adult: false,
    backdrop_path: "/fTLMsF3IVLMcpNqIqJRweGvVwtX.jpg",
    id: 1035806,
    title: "Detective Knight: Independence",
    original_language: "en",
    original_title: "Detective Knight: Independence",
    overview:
      "Detective James Knight 's last-minute assignment to the Independence Day shift turns into a race to stop an unbalanced ambulance EMT from imperiling the city's festivities. The misguided vigilante, playing cop with a stolen gun and uniform, has a bank vault full of reasons to put on his own fireworks show... one that will strike dangerously close to Knight's home.",
    poster_path: "/jrPKVQGjc3YZXm07OYMriIB47HM.jpg",
    media_type: "movie",
    genre_ids: [28, 53, 80],
    popularity: 57.252,
    release_date: "2023-01-20",
    video: false,
    vote_average: 4.2,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/gwRMwljwHoNCyyJVgMA2XC4qPUU.jpg",
    id: 615777,
    title: "Babylon",
    original_language: "en",
    original_title: "Babylon",
    overview:
      "A tale of outsized ambition and outrageous excess, tracing the rise and fall of multiple characters in an era of unbridled decadence and depravity during Hollywood's transition from silent films and to sound films in the late 1920s.",
    poster_path: "/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg",
    media_type: "movie",
    genre_ids: [18, 35],
    popularity: 333.058,
    release_date: "2022-12-22",
    video: false,
    vote_average: 7.852,
    vote_count: 179,
  },
  {
    adult: false,
    backdrop_path: "/9XSux1N1t5jqIR96U4EZlo7QZZS.jpg",
    id: 778946,
    title: "Mission Majnu",
    original_language: "hi",
    original_title: "मिशन मजनू",
    overview:
      "Set in the 1970s, an undercover Indian spy takes on a deadly mission to expose a covert nuclear weapons program in the heart of Pakistan.",
    poster_path: "/2aWWQNECR1fUWYy1nJHhZUlJpnR.jpg",
    media_type: "movie",
    genre_ids: [53, 28, 18],
    popularity: 37.258,
    release_date: "2023-01-20",
    video: false,
    vote_average: 8,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/zdPIWOHuL4nBsvgWwMNnAvNtaJk.jpg",
    id: 640146,
    title: "Ant-Man and the Wasp: Quantumania",
    original_language: "en",
    original_title: "Ant-Man and the Wasp: Quantumania",
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    media_type: "movie",
    genre_ids: [12, 878, 35],
    popularity: 142.543,
    release_date: "2023-02-15",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/qEXDEtIbGXz4iIcau2O2QLUsAq6.jpg",
    id: 899579,
    title: "There's Something Wrong with the Children",
    original_language: "en",
    original_title: "There's Something Wrong with the Children",
    overview:
      "Margaret and Ben take a weekend trip with longtime friends Ellie and Thomas and their two young children. Eventually, Ben begins to suspect something supernatural is occurring when the kids behave strangely after disappearing into the woods overnight.",
    poster_path: "/e49Sr3Lxfk2psYhv1SzQjs7MeGo.jpg",
    media_type: "movie",
    genre_ids: [27, 9648, 53],
    popularity: 96.052,
    release_date: "2023-01-17",
    video: false,
    vote_average: 5.846,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
    id: 436270,
    title: "Black Adam",
    original_language: "en",
    original_title: "Black Adam",
    overview:
      "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    media_type: "movie",
    genre_ids: [14, 28, 878],
    popularity: 1388.422,
    release_date: "2022-10-21",
    video: false,
    vote_average: 7.2,
    vote_count: 3786,
  },
  {
    adult: false,
    backdrop_path: "/vKjOToEeM5HcpczmG79fbUxqzju.jpg",
    id: 934433,
    title: "Scream VI",
    original_language: "en",
    original_title: "Scream VI",
    overview:
      "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter in New York City.",
    poster_path: "/yAwJA1Y2Kt1XdbX72cL4MKtIDs3.jpg",
    media_type: "movie",
    genre_ids: [27, 53, 9648],
    popularity: 83.318,
    release_date: "2023-03-08",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/cJFNCdlWpmLTzHRqbmmOzKjXAjG.jpg",
    id: 858408,
    title: "Dog Gone",
    original_language: "en",
    original_title: "Dog Gone",
    overview:
      "When his beloved dog goes missing, a young man embarks on an incredible search with his parents to find him and give him life-saving medication.",
    poster_path: "/eYWdLZCS9W1Xli9bynzFSddLx02.jpg",
    media_type: "movie",
    genre_ids: [10751, 12, 18],
    popularity: 346.703,
    release_date: "2023-01-13",
    video: false,
    vote_average: 6.67,
    vote_count: 56,
  },
  {
    adult: false,
    backdrop_path: "/g4v4uO0zCBARWdWV3Mv8YijXvz2.jpg",
    id: 1020696,
    title: "Play Dead",
    original_language: "en",
    original_title: "Play Dead",
    overview:
      "Criminology student Chloe fakes her own death to break into a morgue, in order to retrieve a piece of evidence that ties her younger brother to a crime gone wrong. Once inside, she quickly learns that the fearsome Coroner uses the morgue as a front for a sick and twisted business. As a frightening game of cat and mouse ensues, Chloe will discover that the scariest thing about the morgue is not the dead, but the living.",
    poster_path: "/h5bwT8fuE6VIaOslRezwDiL2DxK.jpg",
    media_type: "movie",
    genre_ids: [27, 53],
    popularity: 32.556,
    release_date: "2022-12-09",
    video: false,
    vote_average: 5.5,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/yYrvN5WFeGYjJnRzhY0QXuo4Isw.jpg",
    id: 505642,
    title: "Black Panther: Wakanda Forever",
    original_language: "en",
    original_title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 878],
    popularity: 1111.163,
    release_date: "2022-11-09",
    video: false,
    vote_average: 7.477,
    vote_count: 1661,
  },
  {
    adult: false,
    backdrop_path: "/7tXJhpWe4iEWzWad6DkH9iPpR8b.jpg",
    id: 872954,
    title: "The Old Way",
    original_language: "en",
    original_title: "The Old Way",
    overview:
      "An old gunslinger and his daughter must face the consequences of his past, when the son of a man he murdered years ago arrives to take his revenge.",
    poster_path: "/8HCCYAIocXxMKn7J9yQfDX1vBM5.jpg",
    media_type: "movie",
    genre_ids: [28, 37],
    popularity: 83.457,
    release_date: "2023-01-06",
    video: false,
    vote_average: 6.477,
    vote_count: 22,
  },
];
export default function MoviesTrending() {
  const [moviesData, setMoviesData] = useState(tempData);

  //   useEffect(() => {
  //     movieApi
  //       .getMoviesTrending()
  //       .then((res) => {
  //         const { data } = res;
  //         const { results } = data;

  //         setMoviesData(results);
  //       })
  //       .catch((err) => console.log(err));
  //   }, []);

  return <MoviesList movies={moviesData} />;
}
